version: "3.9"

services:
  api:
    build: .
    container_name: social_api
    ports:
      - "3000:3000"
    environment:
      ADDR: ":3000"
      DB_ADDR: "postgres://postgres:root@social_postgres:5432/social?sslmode=disable"
      DB_MAX_OPEN_CONNS: 30
      DB_MAX_IDLE_CONNS: 30
      DB_MAX_IDLE_TIME: "15m"
      ENV: "development"
    depends_on:
      - postgres

  postgres:
    ports:
      - "5433:5432"
    image: postgres:17
    container_name: social_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: social
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql:ro

volumes:
  pg_data:
