version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql:ro
    ports:
      - "5433:5432"

volumes:
  pg_data:
