name: CI for social project only

on:
  push:
    paths:
      - 'scaffolding-api-server/social'      # Only runs if something inside social/ changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...
      working-directory: social

    - name: Test
      run: go test -v ./...
      working-directory: social
